### ISSUE TITLE
После обычной драки я оказался в притоне и появился результат похода на дело

### ISSUE THREAD

**Issue by bairog** [bolknote/gopnik2#10]
И снова я)
![image](https://user-images.githubusercontent.com/44995181/231360832-30e3ccc3-8933-4d3c-92a6-f78dafd8fc50.png)
Гопником разводил прохожих на деньги, началась драка, я победил и в результате оказался в притоне после якобы выполнения задания.

**Comment by bairog** [comment]
Бес попутал - хлам же у барыг продаётся. Не обращайте внимание)

**Comment by bairog** [comment]
Судя по всему я сильно что-то "сломал", потому что после загрузки сохранения и первой же драки - опять я в притоне:
![image](https://user-images.githubusercontent.com/44995181/231361674-5b6039c7-182a-4ad3-a894-ec1b83113b43.png)
[gop2w_1.sav.zip](https://github.com/bolknote/gopnik2/files/11207572/gop2w_1.sav.zip)

**P.S.** Да, теперь я всегда попадаю в притон. Надо смотреть прикреплённый файл сохранения.
![image](https://user-images.githubusercontent.com/44995181/231368364-82585dde-27b4-45e2-8c4c-09c6cb4df907.png)

**Comment by bairog** [comment]
И только после пятой (кажется) драки я перестал попадать в притон
[gop2w_1.sav.zip](https://github.com/bolknote/gopnik2/files/11207856/gop2w_1.sav.zip)

**Comment by bairog** [comment]
Нет, опять я в притоне
![image](https://user-images.githubusercontent.com/44995181/231369631-35a5e41e-d8fe-456d-b007-81395f2aea78.png)
[gop2w_1.sav.zip](https://github.com/bolknote/gopnik2/files/11207871/gop2w_1.sav.zip)

**Comment by bolknote** [comment]
Какой-то капец. Исходники, которые я подобрал, видимо сильно сломаны ((

Да, буду смотреть что происходит, но тут какая-то прямо сильная беда, судя по всему.

**Comment by bairog** [comment]
Вот ещё вариант развития событий (звонок на мобильный прямо внутри драки и после драки я в притоне):
![image](https://user-images.githubusercontent.com/44995181/231375798-28e1445b-0dfe-4817-bb3a-8b6fd2c1fb4b.png)
[gop2w_1.sav.zip](https://github.com/bolknote/gopnik2/files/11208115/gop2w_1.sav.zip)
> Какой-то капец. Исходники, которые я подобрал, видимо сильно сломаны ((

Вам просто не повезло со мной в качестве тестировщика) Я долго играл в dos-вариант (хотя и довольно давно), многое помню как работало..

**Comment by bolknote** [comment]
За это вам спасибо )) Поправить бы ещё это. Меня этот баг что-то пугает, как бы тут пол-игры не пришлось переписывать )

**Comment by bairog** [comment]
Ещё раз так случилось, уже после "перезагрузки" (тут правда был звонок по мобильному посреди боя):
![image](https://user-images.githubusercontent.com/44995181/231480275-461ee6ef-c13d-459a-9ac1-b5f86ea0ad7a.png)

**Comment by bairog** [comment]
А бывает что в течение одной драки происходит даже по 2 звонка с разными "заданиями" из притона
![image](https://user-images.githubusercontent.com/44995181/231492820-ef4585a9-1728-4b99-826b-ef29c20061d0.png)
Соответственно после победы "выполняются" оба задания
![image](https://user-images.githubusercontent.com/44995181/231493022-664218f9-210d-4ee1-9744-a17a1512a9a1.png)

**Comment by bairog** [comment]
Более того - звонок из притона может быть во время драки внутри самого притона:
![image](https://user-images.githubusercontent.com/44995181/231497953-3e76e3b8-3151-4859-baf2-d714f1ba2948.png)

**Comment by bolknote** [comment]
Мда, как же всё это круто сломано-то

**Comment by bolknote** [comment]
похоже я нашёл как это сломалось
