### ISSUE TITLE
В бою с вахтёршей на Парке Победы на лёгкой сложности у неё 1 245 251 Живучести (6 226 306 здоровья)

### ISSUE THREAD

**Issue by bairog** [bolknote/gopnik2#13]
Проверьте пожалуйста - разве так и должно быть?
![image](https://user-images.githubusercontent.com/44995181/231666296-676247b6-cdc2-4f5a-bea5-b63243ad6ba3.png)
Позвал братву, но её быстро отпинали
![image](https://user-images.githubusercontent.com/44995181/231666770-cb20bba1-6c0d-4d75-9bb4-c02039f04429.png)
Теоретически победить то наверно можно, выпив цистерну пива залпом (но если ввести опьянение, как вы планируете - то тут без шансов). Братву отпинали довольно быстро, а пистолет промахивается да и вообще я бью сильнее :) Как ещё себе помочь - не представляю.. И как я понимаю это не главный враг (комендантша общаги), а только предбосс (вахтёрша)..
**P.S.** И имя врага отображается двумя знаками вопроса - так тоже задумано?

**Comment by bolknote** [comment]
Не, это всё какой-то баг, надо смотреть.

**Comment by bolknote** [comment]
Так а это что за босс-то? У него в начале битвы было какое-то intro?

**Comment by bairog** [comment]
Вахтёрша в общежитии на Парке Победы (станция открывается на 40 уровне). Интро такое:
![image](https://user-images.githubusercontent.com/44995181/231674703-53eeaf75-cf38-4082-a8e3-1fd5667c1606.png)

P, S. Заодно наверно надо глянуть статы финального босса - если у предбосса 6-7 млн здоровья, то боюсь представить, сколько его будет у комендантши)

**Comment by bolknote** [comment]
Я проходил финального босса в этой версии игры, там всё норм было, это что-то сломалось. Боюсь, это опять какие-то баги с сохранением и восстановлением, буду смотреть. Всё-такие очень жаль, что автор порта удалил целые куски кода для работы с сохранениями. Приходится их в муках сейчас самому писать, а я не до конца понимаю что у персонажа надо сохранять, а что нет. Оттуда и ошибки.

**Comment by bairog** [comment]
На всякий случай сохранение на Парке Победы (команда для финального боя - **eog**)- [gop2w_1.zip](https://github.com/bolknote/gopnik2/files/11219052/gop2w_1.zip)

**Comment by bairog** [comment]
Спасибо за фикс - здоровье стало 666 (вполне по силам одолёть её):
![image](https://user-images.githubusercontent.com/44995181/231682810-014e029f-decc-4dd0-956b-02fc99df6ad7.png)

**Comment by bairog** [comment]
У финального босса статы тоже вполне реальные:
![image](https://user-images.githubusercontent.com/44995181/231683627-b83eb428-dc1f-47e7-80dd-cda0e4022f0a.png)
И к слову сказать мне за финальный бой пришлось выпить порядка **20л** пива (**40** бутылок!!!) - и это на **лёгкой** сложности. Если будете изменять логику работы опьянения - имейте это в виду.

**Comment by bolknote** [comment]
Охохо )) Стоит ли трогать вообще эту логику? )) можно попробовать её чуть подтюнить, чтобы на первых парах просто с ног не валило так часто ) а в остальном оставить, как есть.

**Comment by bairog** [comment]
>можно попробовать её чуть подтюнить, чтобы на первых парах просто с ног не валило так часто ) а в остальном оставить, как есть.

На мой взгляд тоже - это самый оптимальный вариант..
