### ISSUE TITLE
Ошибка сборки под Windows 11 x64 Pro 21H2 с MinGW

### ISSUE THREAD

**Issue by bairog** [bolknote/gopnik2#4]
Добрый день.
Windows 11 x64 Pro 21H2, установлен последний MinGW (gcc 6.3.0) [по этой инструкции](https://www.ics.uci.edu/~pattis/common/handouts/mingweclipse/mingw.html). При сборке выдаёт ошибку:

```
E:\gopnik2>make
g++ -Wall -Wpedantic -Wextra -ggdb -std=c++11 -c game.cpp -o game.o
game.cpp: In member function 'int game::add_hero_type(const char*, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int)':
game.cpp:513:37: error: 'strdup' was not declared in this scope
     ht[ht_amount].type = strdup(type);
                                     ^
game.cpp: In member function 'int game::add_hero_phrase(int, const char*, const char*) const':
game.cpp:555:79: error: 'strdup' was not declared in this scope
     ht[ht_index].hero_addr[ht[ht_index].hero_phrase_amount] = strdup(hero_addr);
                                                                               ^
game.cpp: In member function 'int game::add_enemy_phrase(int, const char*, const char*) const':
game.cpp:579:82: error: 'strdup' was not declared in this scope
     ht[ht_index].enemy_addr[ht[ht_index].enemy_phrase_amount] = strdup(enemy_addr);
                                                                                  ^
game.cpp: In member function 'int game::add_location(const char*)':
game.cpp:592:39: error: 'strdup' was not declared in this scope
     loc[loc_amount].name = strdup(name);
                                       ^
game.cpp: In member function 'int game::add_location_command(int, FP, int, const char*, const char*) const':
game.cpp:631:72: error: 'strdup' was not declared in this scope
     loc[loc_index].command[loc[loc_index].comm_amount] = strdup(command);
                                                                        ^
game.cpp: In static member function 'static int game::add_inventory(hero*, const char*, int, int, int, int, int, int, int, int, int)':
game.cpp:663:59: error: 'strdup' was not declared in this scope
     cur_hero->inv[cur_hero->inv_amount].name = strdup(name);
                                                           ^
game.cpp: In member function 'int game::add_w_event(int, int, const char*)':
game.cpp:695:39: error: 'strdup' was not declared in this scope
     we[we_amount].event = strdup(event);
                                       ^
game.cpp: In member function 'int game::add_price_list_memb(int, const char*, const char*, int) const':
game.cpp:735:72: error: 'strdup' was not declared in this scope
     pl[pl_index].members[pl[pl_index].member_amount].name = strdup(name);
                                                                        ^
game.cpp: In member function 'int game::add_buy_phrase(int, int, const char*) const':
game.cpp:762:118: error: 'strdup' was not declared in this scope
     pl[pl_index].members[plm_index].buy_phrase[pl[pl_index].members[plm_index].buy_phrase_amount] = strdup(buy_phrase);
                                                                                                                      ^
game.cpp: In member function 'int game::add_station(const char*, int, const char*)':
game.cpp:778:39: error: 'strdup' was not declared in this scope
     stn[stn_amount].name = strdup(name);
                                       ^
game.cpp: In member function 'int game::start()':
game.cpp:2236:42: error: '_fileno' was not declared in this scope
         int save = _setmode(_fileno(stdin), _O_U16TEXT);
                                          ^
game.cpp:2236:45: error: '_O_U16TEXT' was not declared in this scope
         int save = _setmode(_fileno(stdin), _O_U16TEXT);
                                             ^~~~~~~~~~
make: *** [game.o] Error 1
```

В чём может быть проблема?

**Comment by bolknote** [comment]
Под Windows своя атмосфера, я буквально вчера доделал сборку под эту ОС, попробуйте `make mingw`, должно собраться.

**Comment by bairog** [comment]
К сожалению не помогло:
```
E:\gopnik2>make mingw
x86_64-w64-mingw32-g++ -Wall -Wpedantic -Wextra -ggdb -std=c++11 -static -mno-ms-bitfields -c game.cpp -o game.o
make: x86_64-w64-mingw32-g++: Command not found
make: *** [game.o] Error 127
```
> я буквально вчера доделал сборку под эту ОС

У вас на виртуальной машине с Windows и MinGW собирается без проблем?

**Comment by bolknote** [comment]
Я собираю под «Мак», но запускаю на Винде, я меня Виндоуз в какой-то степени терра инкогнита )
А если открыть Makefile блокнотом и заменить `x86_64-w64-mingw32-g++` на `g++`, то получается скомпилировать? )

**Comment by bairog** [comment]
> А если открыть Makefile блокнотом и заменить `x86_64-w64-mingw32-g++` на `g++`, то получается скомпилировать? )

Та же ошибка, что и в первом сообщении (собственно там судя по первой строчке и так `g++` выбирался).

**Comment by bolknote** [comment]
> Та же ошибка, что и в первом сообщении (собственно там первой строчкой и так g++ выбирается).

Блин, надо похоже попробовать собрать прямо на Виндоуз, я так ещё не пробовал. Могу пока собранный файл приложить, если так подойдёт.

**Comment by bolknote** [comment]
[gop2.exe](https://github.com/bolknote/gopnik2/files/11167789/gop2.exe.zip)

**Comment by bairog** [comment]
Спасибо. На первый взгляд всё штатно - запустилось без "бубна", загрузка/сохранение работает, команда `run` - огонь :).

**Comment by bolknote** [comment]
На этой неделе попробую собрать на Windows и посмотреть в чём там дело, ни разу так ещё не пробовал )

**Comment by bairog** [comment]
После вашего исправления [8ad837b](https://github.com/bolknote/gopnik2/commit/8ad837b5a02de1c33b5d31c62bccb9a9cf3562f9) игра технически собралась, правда размер **gop2.exe** у меня получился почти 2 раза больше (**1 379 605** байт против **725 843** байт у вашего файла двумя сообщениями выше).
Вот что выводит ваш файл по команде **s** (инфо о персонаже) - всё выглядит нормально:
![image](https://user-images.githubusercontent.com/44995181/230364474-b18b40a9-cffa-495d-a90e-6d6153de4abe.png)
Вот что выводит скомпилированный файл - какие то проблемы с загрузкой сохранения:
![image](https://user-images.githubusercontent.com/44995181/230364554-8802696c-6267-49f8-8775-a1c631efd449.png)

Скомпилированный файл и сохранение - [gopnik2.zip](https://github.com/bolknote/gopnik2/files/11170099/gopnik2.zip)

**Comment by bolknote** [comment]
Надо взять последнюю версию, там были проблемы с упаковкой структуры для сохранения персонажа, которые я только-только победил.

**Comment by bolknote** [comment]
<img width="935" alt="Снимок экрана 2023-04-07 в 00 26 02" src="https://user-images.githubusercontent.com/392509/230497079-773a4513-83ef-479e-b43d-ea3e73bfd6dd.png">

Вот как у меня это выглядит.

**Comment by bairog** [comment]
Выкачал репозиторий, собрал и пытаюсь загрузить тот же файл сохранения - падает на команде **s** (инфо о персонаже):
![1](https://user-images.githubusercontent.com/44995181/230545001-e6c4fc5f-c097-44dc-868e-b63b061f2e4b.gif)
И дело судя по всему не в уже имевшемся у меня файле сохранения, потому что я попробовал пересохраниться через команду **sav** (размер файла стал меньше - **1 883** байт против **2 618** байт) и загрузиться - опять же таки падает на команде **s**.
И даже если начать новую игру, сразу сохраниться (**sav**) и загрузиться (**loa**) - тоже падает на команде **s**.
Собственно падает даже, если не сохраняться - прямо на команде **s** в любом месте:
![1](https://user-images.githubusercontent.com/44995181/230545334-90e0f531-0743-4ca1-8ec9-d24bedb5a65b.gif)
На всякий случай мой собранный exe и 2 файла сохранения - [gopnik2.zip](https://github.com/bolknote/gopnik2/files/11176128/gopnik2.zip)

**P. S.** Наверно нужно все наши с вами последние сообщения в отдельный issue переместить. проблема то сборки как таковой действительно исправлена - а это судя по всему уже новая проблема..

**Comment by bolknote** [comment]
Да, лучше бы отдельным issue, и напишите, пожалуйста, как собирали, — версии mingw, gcc, make, операционки, чтобы я попробовал как-то воспроизвести проблему. Очевидно, что это опять что-то с упаковкой структуры, но что именно не так — непонятно.

**Comment by bairog** [comment]
Создал новый issue #5.
Версию ОС написал, MinGW ставил по инструкции - по идее можно сделать ВМ с такими же данными и на ней отладиться
