### ISSUE TITLE
Неправильная работа команды S (инфо о персонаже) под Windows 11 x64 Pro 21H2 с MinGW (gcc 6.3.0)

### ISSUE THREAD

**Issue by bairog** [bolknote/gopnik2#5]
После вашего исправления [8ad837b](https://github.com/bolknote/gopnik2/commit/8ad837b5a02de1c33b5d31c62bccb9a9cf3562f9) игра технически собралась, правда размер **gop2.exe** у меня получился почти 2 раза больше (**1 379 605** байт против **725 843** байт у вашего файла двумя сообщениями выше).
Вот что выводит ваш файл по команде **s** (инфо о персонаже) - всё выглядит нормально:
![image](https://user-images.githubusercontent.com/44995181/230364474-b18b40a9-cffa-495d-a90e-6d6153de4abe.png)
Вот что выводит скомпилированный файл - какие то проблемы с загрузкой сохранения:
![image](https://user-images.githubusercontent.com/44995181/230364554-8802696c-6267-49f8-8775-a1c631efd449.png)

Скомпилированный файл и сохранение - [gopnik2.zip](https://github.com/bolknote/gopnik2/files/11170099/gopnik2.zip)   

Windows 11 x64 Pro **21H2**, установлен последний MinGW [по этой инструкции](https://www.ics.uci.edu/~pattis/common/handouts/mingweclipse/mingw.html) (gcc (MinGW.org GCC-6.3.0-1), GNU Make 3.81).

**Comment by bairog** [comment]
Выкачал репозиторий, собрал и пытаюсь загрузить тот же файл сохранения - падает на команде **s** (инфо о персонаже):
![1](https://user-images.githubusercontent.com/44995181/230545001-e6c4fc5f-c097-44dc-868e-b63b061f2e4b.gif)
И дело судя по всему не в уже имевшемся у меня файле сохранения, потому что я попробовал пересохраниться через команду **sav** (размер файла стал меньше - **1 883** байт против **2 618** байт) и загрузиться - опять же таки падает на команде **s**.
И даже если начать новую игру, сразу сохраниться (**sav**) и загрузиться (**loa**) - тоже падает на команде **s**.
Собственно падает даже, если не сохраняться - прямо на команде **s** в любом месте:
![1](https://user-images.githubusercontent.com/44995181/230545334-90e0f531-0743-4ca1-8ec9-d24bedb5a65b.gif)
На всякий случай мой собранный exe и 2 файла сохранения - [gopnik2.zip](https://github.com/bolknote/gopnik2/files/11176128/gopnik2.zip)

**Comment by bolknote** [comment]
Игра собрана через `make`?

В два раза больше получилось, потому что я ещё сжал её при помощи `upx`.

**Comment by bolknote** [comment]
Воу, насколько я вижу по имени файла сохранения, это ещё старая сборка.

Не могли бы взять более новую версию из вкладки «Code» (зелёная кнопка) тут: https://github.com/bolknote/gopnik2/ Там надо выбрать «Download ZIP».

я похоже релиз не сделал что ли… Буквы «w» у нормальной версии быть не должно.

**Comment by bairog** [comment]
> Игра собрана через `make`?

Да, через make.
> Не могли бы взять более новую версию из вкладки «Code» (зелёная кнопка) тут: https://github.com/bolknote/gopnik2/ Там надо выбрать «Download ZIP».

Внезапно через «Download ZIP» всё заработало. Непонятно почему так, я выгружал репозиторий через Git до последнего коммита, перед тем как собирал. Сейчас ещё потестирую..

**Comment by bairog** [comment]
> Буквы «w» у нормальной версии быть не должно.

Файл сохранения всё также называется **gop2w_1.sav**. Правда команда **s** теперь заработала - [gopnik2-main.zip](https://github.com/bolknote/gopnik2/files/11177450/gopnik2-main.zip)

> Ты выпил слишком много пива за раз и опьянел. Лв -1

Это какое то ваше нововведение? В оригинальной версии я не припомню такого антиэффекта от "лечения" пивом. Где можно почитать весь список - я только про возможность убежать из драки через **run** знаю..

**Comment by bolknote** [comment]
> Файл сохранения всё также называется gop2w_1.sav
Блин, забыл убрать это место, уберу скоро букву, надо будет файл сохранения переименовать только
> Это какое то ваше нововведение?..
Не, это не моё, возможно всё же было в оригинале, либо добавил автор, который делал попытку портирования.

От меня добавлено несколько вещей (помимо исправленных багов):
- добавлена новая станция метро (пока не дописана)
- два перснажа, которые были в коде, но закоментированы — охранник и ещё кто-то
- команда «run» на лёгком уровне

Это всё отсебятина, остальное должно быть как в оригинале. Но какие вещи мог сломать чувак, который портировал игру, а какие не работали сразу — я не знаю, починил все логические ошибки, которые нашёл (эффекти от пива к ним не относится).
