### ISSUE TITLE
В драке **Тебе сломали челюсть** и **Тебе сломали ногу** выводится не красным цветом

### ISSUE THREAD

**Issue by bairog** [bolknote/gopnik2#6]
Добрый день, это снова я :)
В драке **Тебе сломали челюсть** и **Тебе сломали ногу** не красным цветом (только по команде **s** уже после драки): 
![image](https://user-images.githubusercontent.com/44995181/230835363-267bb1ce-9816-4828-b431-3ef590e4eb7b.png)
В оригинальной версии эти "критические" повреждения выделялись цветом в драке.

**Comment by bolknote** [comment]
Спасибо!

Лучше бы разбить на три разные issue, так как если я буду делать коммиты, каждый из них будет автоматически закрывать этот issue.

1) под Linux точно работало,  похоже сломал, а под Windows скорее всего не работало никогда, я посмотрю
2) а это я, похоже, сломал когда исходники чистил, должно было поправиться одним из последних коммитов, буду тестировать
3) логика пива мне такой досталось. а про 0,5л и бутылки я не понял. бутылка же может быть 0,5 литра?

**Comment by bolknote** [comment]
Пункт №2 поправил.

**Comment by bolknote** [comment]
По логике кода у персонажа есть «лимит опьянения», он как-то связан с прокачкой персонажа.

**Comment by bairog** [comment]
> Лучше бы разбить на три разные issue, так как если я буду делать коммиты, каждый из них будет автоматически закрывать этот issue.

Создал отдельные issue - #7 и #8 

> 3. логика пива мне такой досталось. а про 0,5л и бутылки я не понял. бутылка же может быть 0,5 литра?

Бутылка судя по всему как раз и равна 0,5л. Но тогда либо на рынке должно быть **Пиво 1 бутылка**, либо в инвентаре (и при использовании) не бутылки, а величина, кратная **0,5л**. Чтобы везде одинаковая единица измерения была.

**Comment by bairog** [comment]
> Лучше бы разбить на три разные issue, так как если я буду делать коммиты, каждый из них будет автоматически закрывать этот issue.

Создал отдельные issue для каждой проблемы - #7, #8 и #9
