### ISSUE TITLE
При повторении предыдущей команды (стрелка вверх) под Windows - выводится символ H

### ISSUE THREAD

**Issue by bairog** [bolknote/gopnik2#7]
При повторении предыдущей команды (стрелка вверх) под Windows - выводится символ H (вне зависимости от того, какой в реальности была предыдущая команда). В драке очень неудобно - вместо того, чтобы просто повторять команду удала k приходится каждый раз вбивать её с клавиатуры заново. В оригинальной версии "Гопник 2" это точно работало без проблем.

**Comment by bolknote** [comment]
Это в 1.21 исправлено.
