### ISSUE TITLE
Опьянение наступает даже от первой же бутылки пива (как минимум на 1м уровне прокачки персонажа)

### ISSUE THREAD

**Issue by bairog** [bolknote/gopnik2#8]
Всё же непонятно как работает опъянение от пива - достаточно выпить один раз и уже **Ты выпил слишком много пива за раз и опьянел. . Лв -1**:
![image](https://user-images.githubusercontent.com/44995181/230837012-48be6fbf-dfe3-4c77-ae84-3e4aaf1c1490.png)
В оригинальной игре опьянение насколько я помню наступало только после команды "Набухаться в хлам" - **mh** (что весьма логично). Под "оригинальной игрой" я подразумеваю [это](https://playminigames.ru/game/gopnik-2). У меня ещё на диске оно есть в виде **gop2.exe**, но откуда я его брал - точно не помню. Может быть с old-games..

Если есть возможность это исправить - было бы отлично. Спасибо.

**Comment by bairog** [comment]
> По логике кода у персонажа есть «лимит опьянения», он как-то связан с прокачкой персонажа.

Вот это внезапно.. В варианте, в который играл я опьянение наступало явно не от первой же бутылки (даже на 1м уровне персонажа). Это кажется логичным, иначе от "лечения" пивом в бою больше проблем получается.

**Comment by bairog** [comment]
На 6м уровне персонажа опьянение всё также наступает после первой же бутылки (хоть в драке, хоть после неё). 
![image](https://user-images.githubusercontent.com/44995181/231362331-e49c99f2-83f7-4b47-bec6-733151fb41d9.png)
Кажется эта механика всё же работает не совсем правильно..

**Comment by bolknote** [comment]
Там не от уровня персонажа зависит, а от количества пройденных районов (по мере роста персонажа он перемещается из района в район, пока не доходит до финальной битвы, на которую нельзя попасть, пока не прошёл сколько-то там районов).

Не вполне ясно что делать с этой логикой. По всей видимости эта логика в исходниках — от автора оригинальной игры (тот человек, который портировал игру сказал, что в логике ничего не менял) и у меня только две теории:

1) это какие-то промежуточные исходники, версия под DOS — чуть более поздняя версия с немного другой логикой
2) это наоборот недописанные исходники следующей версии, версия под DOS чуть более старая

**Comment by bairog** [comment]
Когда/если будет время/желание логику всё же надо будет доработать. Иначе сейчас в битве можно выпить пива только 1 раз - а действие скорее отрицательное (здоровье **+5**, но уровень **-1**, что явно хуже). Ерунда какая то получается - более сильного противника не победить никак. А убежать через **run** можно только до начала битвы и только на лёгком уровне..

**Comment by bolknote** [comment]
В битве через run тоже можно убежать, но только на начальном уровне, да.

А какие предложения? Как работала эта логика в оригинале? Никогда не давало опьянения? Мне кажется по логике какой-то порог должен быть — если выпил (скажем) 1,5 литра, то опьянел.

**Comment by bairog** [comment]
В DOS-варианте по команде **mh** (насколько помню - это разом выпить объём пива, достаточный для восстановления всего здоровья до максимума) опьянение точно наступало (причём вне зависимости 0.5л ты выпил или 5.5л). 
А если пить много раз "по одной" - опьянения как я помню не наступало (даже на 1м уровне и даже если выпить эти 5.5л по 0.5л за 11 команд **h**). Очевидно, что это тоже неправильно - но уже в другую сторону (упрощает игру). 
Мне кажется надо ввести какое-то стартовое значение (пусть это будет как раз 1.5л), а дальше шанс не опьянеть от каждой последующей бутылки. Изначально шанс равен 0% и растёт от какого то параметра персонажа (например, уровня). Потому что в финальной драке точно понадобится выпить литров 10 пива, чтобы подлечиться в бою (по крайней мере в DOS-версии без этого было не победить даже на лёгком уровне).

**Comment by bolknote** [comment]
<img width="640" alt="Снимок экрана 2023-04-12 в 13 34 41" src="https://user-images.githubusercontent.com/392509/231432548-1215b473-24dc-4044-b14f-16446ee7c6eb.png">

В версии под DOS действительно никакого опьянения. Надо подумать, потому что это тоже как дисбаланс смотрится. Схема «пьянеть» с какого-то значения, чем больше сила, тем выше, мне кажется нормальной, только в какую-то формулу надо её превратить.

**Comment by bairog** [comment]
> Схема «пьянеть» с какого-то значения, чем больше сила, тем выше, мне кажется нормальной, только в какую-то формулу надо её превратить.

Силу очень долго нельзя прокачать (в качалке после 25 уровня это становится доступно). А при получении нового уровня как я понимаю прибавляется случайная характеристика персонажа. Там что отталкиваться именно от уровня, имхо, надёжнее. Ну или от живучести (и в этом есть логика - "выносливый" алкаш :)) - её можно качать как только открывается качалка в Купчино (на самых начальных уровнях персонажа).

**P. S.** И к слову сказать мне за финальный бой пришлось выпить порядка **20л** пива (**40** бутылок!!!) - и это на **лёгкой** сложности. Если изменять логику работы опьянения - имейте это в виду.

**Comment by bolknote** [comment]
Логика теперь такая: я оставил зависимости от кол-ва открытый районов («крутости») перса, но ввёл новый фактор из-за которого при количестве открытых районов =0 шанс опьянеть 10% и начинает расти на 15% с каждой выпитой бутылкой. Кажется это норм.
